In [1]:
import pandas as pd

ruta = 'C:/Users/Sistemas/Desktop/proyecto_pallets/data/enero_pallets.xlsx'

df = pd.read_excel (ruta)

df.head()

,Unnamed: 0,Unnamed: 1,2025-01-04 00:00:00,2025-01-06 00:00:00,2025-01-07 00:00:00,2025-01-08 00:00:00,2025-01-09 00:00:00,2025-01-10 00:00:00,2025-01-11 00:00:00,2025-01-13 00:00:00,...,2025-01-30 00:00:00,2025-01-31 00:00:00,Unnamed: 26,Promedio pallets por socio diario,Porcentaje pallets por socio,base,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,17,17,24,22,37,27,24,25,...,18,15,NaN,21,0.025547,10,8.430657,18.430657,-2.569343,11
1,5.0,GARMENDIA HUGO,55,52,47,55,5,54,53,59,...,59,57,NaN,48,0.058394,10,19.270073,29.270073,-18.729927,38
2,8.0,GRAZIOSI MIRTHA,50,46,50,31,53,40,42,45,...,34,37,NaN,40,0.048662,10,16.058394,26.058394,-13.941606,30
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,18,17,14,9,12,13,15,15,...,8,8,NaN,11,0.013382,10,4.416058,14.416058,3.416058,1
4,10.0,ROSICA GABRIEL,15,13,8,14,10,12,12,12,...,4,11,NaN,10,0.012165,10,4.014599,14.014599,4.014599,0

In [2]:
df.rename(columns={'Unnamed: 0': 'id_socio', 'Unnamed: 1': 'socio'}, inplace=True)

In [ ]:
df_melted = pd.melt(df, 
                    id_vars=['id_socio', 'socio'], 
                    value_vars=df.columns[2:26], 
                    var_name='fecha', 
                    value_name='pallets')

# Convertir la columna 'fecha' a tipo datetime
df_melted['fecha'] = pd.to_datetime(df_melted['fecha'])

df_melted.head()

   id_socio                             socio      fecha  pallets
0       3.0                        DOZ CARLOS 2025-01-04       17
1       5.0                    GARMENDIA HUGO 2025-01-04       55
2       8.0                  GRAZIOSI MIRTHA  2025-01-04       50
3       9.0  PACI ANTONIO - DIGIANO JAVIER SH 2025-01-04       18
4      10.0                    ROSICA GABRIEL 2025-01-04       15

In [5]:
df_melted.to_excel('df_melted_exportado.xlsx', index=False)

In [6]:
# Realizar el merge para asociar las columnas adicionales
df_enriched = pd.merge(df_melted, df[['id_socio', 'socio', 'base', 'Promedio pallets por socio diario', 
                                      'Porcentaje pallets por socio', 'Parte variable', 
                                      'Total final por socio', 'Exceso Palets contra (Fijo+Variable)', 
                                      'Exceso contra Fijo']], 
                       on=['id_socio', 'socio'], 
                       how='left')

df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-01-04,17,10,21,0.025547,8.430657,18.430657,-2.569343,11
1,5.0,GARMENDIA HUGO,2025-01-04,55,10,48,0.058394,19.270073,29.270073,-18.729927,38
2,8.0,GRAZIOSI MIRTHA,2025-01-04,50,10,40,0.048662,16.058394,26.058394,-13.941606,30
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-01-04,18,10,11,0.013382,4.416058,14.416058,3.416058,1
4,10.0,ROSICA GABRIEL,2025-01-04,15,10,10,0.012165,4.014599,14.014599,4.014599,0

In [8]:
df_enriched.to_excel('df_melted_exportado.xlsx', index=False)

In [9]:
df_enriched['Porcentaje pallets por socio'] = df_enriched['Porcentaje pallets por socio'] * 100
df_enriched['Porcentaje pallets por socio'] = df_enriched['Porcentaje pallets por socio'].map('{:.2f}%'.format)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-01-04,17,10,21,2.55%,8.430657,18.430657,-2.569343,11
1,5.0,GARMENDIA HUGO,2025-01-04,55,10,48,5.84%,19.270073,29.270073,-18.729927,38
2,8.0,GRAZIOSI MIRTHA,2025-01-04,50,10,40,4.87%,16.058394,26.058394,-13.941606,30
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-01-04,18,10,11,1.34%,4.416058,14.416058,3.416058,1
4,10.0,ROSICA GABRIEL,2025-01-04,15,10,10,1.22%,4.014599,14.014599,4.014599,0

In [10]:
df_enriched['Parte variable'] = df_enriched['Parte variable'].astype(int)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-01-04,17,10,21,2.55%,8,18.430657,-2.569343,11
1,5.0,GARMENDIA HUGO,2025-01-04,55,10,48,5.84%,19,29.270073,-18.729927,38
2,8.0,GRAZIOSI MIRTHA,2025-01-04,50,10,40,4.87%,16,26.058394,-13.941606,30
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-01-04,18,10,11,1.34%,4,14.416058,3.416058,1
4,10.0,ROSICA GABRIEL,2025-01-04,15,10,10,1.22%,4,14.014599,4.014599,0

In [11]:
df_enriched['Total final por socio'] = df_enriched['Total final por socio'].astype(int)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-01-04,17,10,21,2.55%,8,18,-2.569343,11
1,5.0,GARMENDIA HUGO,2025-01-04,55,10,48,5.84%,19,29,-18.729927,38
2,8.0,GRAZIOSI MIRTHA,2025-01-04,50,10,40,4.87%,16,26,-13.941606,30
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-01-04,18,10,11,1.34%,4,14,3.416058,1
4,10.0,ROSICA GABRIEL,2025-01-04,15,10,10,1.22%,4,14,4.014599,0

In [12]:
df_enriched['Exceso Palets contra (Fijo+Variable)'] = df_enriched['Exceso Palets contra (Fijo+Variable)'].astype(int)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-01-04,17,10,21,2.55%,8,18,-2,11
1,5.0,GARMENDIA HUGO,2025-01-04,55,10,48,5.84%,19,29,-18,38
2,8.0,GRAZIOSI MIRTHA,2025-01-04,50,10,40,4.87%,16,26,-13,30
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-01-04,18,10,11,1.34%,4,14,3,1
4,10.0,ROSICA GABRIEL,2025-01-04,15,10,10,1.22%,4,14,4,0

In [13]:
df_enriched.to_excel('df_melted_exportado.xlsx', index=False)