In [15]:
import pandas as pd

ruta = 'C:/Users/Sistemas/Desktop/proyecto_pallets/data/marzo_pallets.xlsx'

df = pd.read_excel (ruta)

df.head()

,Unnamed: 0,Unnamed: 1,2025-03-01 00:00:00,2025-03-05 00:00:00,2025-03-06 00:00:00,2025-03-07 00:00:00,2025-03-08 00:00:00,2025-03-10 00:00:00,2025-03-11 00:00:00,2025-03-12 00:00:00,...,2025-03-29 00:00:00,2025-03-31 00:00:00,Unnamed: 25,Promedio pallets por socio diario,Porcentaje pallets por socio,base,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,24,20,19,24,20,21,24,24,...,19,15,NaN,19,0.030000,10,9.900000,19.900000,0.000000,9
1,5.0,GARMENDIA HUGO,38,44,39,43,45,45,51,41,...,11,15,NaN,35,0.054945,10,18.131868,28.131868,-6.868132,25
2,8.0,GRAZIOSI MIRTHA,20,11,12,17,19,19,19,26,...,42,42,NaN,28,0.043956,10,14.505495,24.505495,-3.000000,18
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,8,9,11,10,16,16,15,13,...,7,7,NaN,10,0.015699,10,5.180534,15.180534,5.000000,0
4,10.0,ROSICA GABRIEL,7,9,3,4,7,8,5,6,...,5,5,NaN,6,0.009419,10,3.108320,13.108320,7.000000,-4

In [16]:
df.rename(columns={'Unnamed: 0': 'id_socio', 'Unnamed: 1': 'socio'}, inplace=True)

In [17]:
df_melted = pd.melt(df, 
                    id_vars=['id_socio', 'socio'], 
                    value_vars=df.columns[2:24], 
                    var_name='fecha', 
                    value_name='pallets')

# Convertir la columna 'fecha' a tipo datetime
df_melted['fecha'] = pd.to_datetime(df_melted['fecha'])

df_melted.head()

   id_socio                             socio      fecha  pallets
0       3.0                        DOZ CARLOS 2025-03-01       24
1       5.0                    GARMENDIA HUGO 2025-03-01       38
2       8.0                  GRAZIOSI MIRTHA  2025-03-01       20
3       9.0  PACI ANTONIO - DIGIANO JAVIER SH 2025-03-01        8
4      10.0                    ROSICA GABRIEL 2025-03-01        7

In [18]:
# Realizar el merge para asociar las columnas adicionales
df_enriched = pd.merge(df_melted, df[['id_socio', 'socio', 'base', 'Promedio pallets por socio diario', 
                                      'Porcentaje pallets por socio', 'Parte variable', 
                                      'Total final por socio', 'Exceso Palets contra (Fijo+Variable)', 
                                      'Exceso contra Fijo']], 
                       on=['id_socio', 'socio'], 
                       how='left')

df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-03-01,24,10,19,0.030000,9.900000,19.900000,0.000000,9
1,5.0,GARMENDIA HUGO,2025-03-01,38,10,35,0.054945,18.131868,28.131868,-6.868132,25
2,8.0,GRAZIOSI MIRTHA,2025-03-01,20,10,28,0.043956,14.505495,24.505495,-3.000000,18
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-03-01,8,10,10,0.015699,5.180534,15.180534,5.000000,0
4,10.0,ROSICA GABRIEL,2025-03-01,7,10,6,0.009419,3.108320,13.108320,7.000000,-4

In [19]:
df_enriched['Porcentaje pallets por socio'] = df_enriched['Porcentaje pallets por socio'] * 100
df_enriched['Porcentaje pallets por socio'] = df_enriched['Porcentaje pallets por socio'].map('{:.2f}%'.format)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-03-01,24,10,19,3.00%,9.900000,19.900000,0.000000,9
1,5.0,GARMENDIA HUGO,2025-03-01,38,10,35,5.49%,18.131868,28.131868,-6.868132,25
2,8.0,GRAZIOSI MIRTHA,2025-03-01,20,10,28,4.40%,14.505495,24.505495,-3.000000,18
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-03-01,8,10,10,1.57%,5.180534,15.180534,5.000000,0
4,10.0,ROSICA GABRIEL,2025-03-01,7,10,6,0.94%,3.108320,13.108320,7.000000,-4

In [20]:
df_enriched['Parte variable'] = df_enriched['Parte variable'].astype(int)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-03-01,24,10,19,3.00%,9,19.900000,0.000000,9
1,5.0,GARMENDIA HUGO,2025-03-01,38,10,35,5.49%,18,28.131868,-6.868132,25
2,8.0,GRAZIOSI MIRTHA,2025-03-01,20,10,28,4.40%,14,24.505495,-3.000000,18
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-03-01,8,10,10,1.57%,5,15.180534,5.000000,0
4,10.0,ROSICA GABRIEL,2025-03-01,7,10,6,0.94%,3,13.108320,7.000000,-4

In [21]:
df_enriched['Total final por socio'] = df_enriched['Total final por socio'].astype(int)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-03-01,24,10,19,3.00%,9,19,0.000000,9
1,5.0,GARMENDIA HUGO,2025-03-01,38,10,35,5.49%,18,28,-6.868132,25
2,8.0,GRAZIOSI MIRTHA,2025-03-01,20,10,28,4.40%,14,24,-3.000000,18
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-03-01,8,10,10,1.57%,5,15,5.000000,0
4,10.0,ROSICA GABRIEL,2025-03-01,7,10,6,0.94%,3,13,7.000000,-4

In [22]:
df_enriched['Exceso Palets contra (Fijo+Variable)'] = df_enriched['Exceso Palets contra (Fijo+Variable)'].astype(int)
df_enriched.head()

,id_socio,socio,fecha,pallets,base,Promedio pallets por socio diario,Porcentaje pallets por socio,Parte variable,Total final por socio,Exceso Palets contra (Fijo+Variable),Exceso contra Fijo
0,3.0,DOZ CARLOS,2025-03-01,24,10,19,3.00%,9,19,0,9
1,5.0,GARMENDIA HUGO,2025-03-01,38,10,35,5.49%,18,28,-6,25
2,8.0,GRAZIOSI MIRTHA,2025-03-01,20,10,28,4.40%,14,24,-3,18
3,9.0,PACI ANTONIO - DIGIANO JAVIER SH,2025-03-01,8,10,10,1.57%,5,15,5,0
4,10.0,ROSICA GABRIEL,2025-03-01,7,10,6,0.94%,3,13,7,-4

In [23]:
df_enriched.to_excel('df_melted_exportado.xlsx', index=False)